[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit AHTX0
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    tzapu/WiFiManager@^2.0.17